export const DestinationsList = [
  { name: 'Hunza' },
  { name: 'KUMRAT' },
  { name: 'MURREE' },
  { name: 'NARAN' },
  { name: 'SWAT' },
  { name: 'KASHMIR' },
  { name: 'Kalam' },
  { name: 'Ratti Galli' },
  { name: 'Bara Pani' },
  { name: 'Khamosh Waterfall' },
  { name: 'Khaplu Palace' },
  { name: 'Kharpocho Fort' },
  { name: 'Sarfaranga Desert' },
  { name: 'Shangrila Resort' },
  { name: 'Raikot Bridge' },
  { name: 'Fairy Meadows & Beyal Camp Nanga Parbat' },
  { name: 'Arang kel & Taobat Village' },
  { name: 'Ratti Gali Lake' },
  { name: 'Dowarian' },
  { name: 'Neelam River' },
  { name: 'Mingora city' },
  { name: 'Besal' },
  { name: 'Kunhar River' },
  { name: 'Shandur Polo Festival' },
  { name: 'Ghizar Valley' },
  { name: 'Shounter Valley' },
  { name: 'Swaik Lake, Kalar Kahar' },
  { name: 'khatas raj temple' },
  { name: 'Rohtas Fort' },
  { name: 'Khaplu Fort & Village' },
  { name: 'Shigar Valley' },
  { name: 'Chunda Valley' },
  { name: 'Leepa Valley' },
  { name: 'Kala chasma' },
  { name: 'Baboon Valley ' },
  { name: 'Rakaposhi Base Camp' },
  { name: 'China Border' },
  { name: 'Taki Top' },
  { name: 'Thal' },
  { name: 'Tattu Village' },
  { name: 'Batakundi' },
  { name: 'Rama Lake' },
  { name: 'Nathia Gali' },
  { name: 'Passu Cones' },
  { name: 'Siri Paye, Kaghan' },
  { name: 'Nanga Parbat Base Camp' },
  { name: 'Gojal' },
  { name: 'Chilam Joshi Festival' },
  { name: 'Dagri Bangla' },
  { name: 'Phander Valley' },
  { name: 'Katora Lake' },
  { name: 'Base Camp' },
  { name: 'Markhor View Point' },
  { name: 'Toli Peer' },
  { name: 'Chitral' },
  { name: 'Miranjani Top' },
  { name: 'Manthokha Waterfall' },
  { name: 'Khewra Salt Mines' },
  { name: 'K2 Basecamp' },
  { name: 'Satpara Lake' },
  { name: 'Passu Village' },
  { name: 'Nalli Waterfall' },
  { name: 'Soon Valley' },
  { name: 'Ayubia' },
  { name: 'Sharan' },
  { name: 'Kalam Valley' },
  { name: 'Mashkpuri Top' },
  { name: 'Sost' },
  { name: 'Nanga Parbat Raikot Face' },
  { name: 'Ganga Choti' },
  { name: 'Shigar Fort' },
  { name: 'Shigar Cold Desert' },
  { name: 'Upper Kachura Lake' },
  { name: 'Shangrilla Lake' },
  { name: 'Lower Kachura Lake' },
  { name: 'Mansehra' },
  { name: 'Abbottabad' },
  { name: 'Rakaposhi View Point' },
  { name: 'Matiltan Waterfall' },
  { name: 'Mahodand Lake' },
  { name: 'Kel, Neelum Valley' },
  { name: 'Kutton Waterfall' },
  { name: 'Dhani Waterfall' },
  { name: 'Kewai Waterfall' },
  { name: 'Ushu Forest' },
  { name: 'Neelum Valley AJK' },
  { name: 'Beyal Camp' },
  { name: 'Rawalakot' },
  { name: 'Malam Jabba' },
  { name: 'Kallar Kahar' },
  { name: 'Pakpattan' },
  { name: 'Pir Chinasi, Muzaffarabad' },
  { name: 'Kundal Shahi Waterfall' },
  { name: 'Ratti Gali Lake, Dowarian' },
  { name: 'Keran, Neelum Valley' },
  { name: 'Besham City' },
  { name: 'Dunga Gali' },
  { name: 'Moola Chootak' },
  { name: 'Karachi' },
  { name: 'Gwadar' },
  { name: 'Kund Malir' },
  { name: 'Domel' },
  { name: 'Minimarg' },
  { name: 'Astore' },
  { name: 'Uchal Lake' },
  { name: 'Kalash' },
  { name: 'Khanpur Dam' },
  { name: 'Khunjerab Pass' },
  { name: 'Basho Valley' },
  { name: 'Taobat' },
  { name: 'Khaplu Valley and Palace' },
  { name: 'Snow Lake' },
  { name: 'Katpana Cold Desert and Lake' },
  { name: 'Passu Cones and Glacier' },
  { name: 'Baltit Fort' },
  { name: 'Altit Fort' },
  { name: 'Attabad Lake' },
  { name: 'Shangrila Lake' },
  { name: 'Siri Paye Meadows' },
  { name: 'Queen Dudipastar Lake' },
  { name: 'Jahaz Banda' },
  { name: 'Nanga Parbat' },
  { name: 'Sharda' },
  { name: 'Shogran' },
  { name: 'Gaban Jabba' },
  { name: 'Deosai Plains' },
  { name: 'Skardu' },
  { name: 'Muzaffarabad' },
  { name: 'Lahore' },
  { name: 'Lalusar Lake' },
  { name: 'Aansoo Lake' },
  { name: 'Naltar Valley' },
  { name: 'Fairy Meadows' },
  { name: 'Hunza Valley' },
  { name: 'Kaghan' },
  { name: 'Saif-ul-Malook Lake' },
  { name: 'Balochistan' },
  { name: 'Ormara Beach' },
  { name: 'Nanga Parbat View Point' },
  { name: 'Islamabad' },
  { name: 'Balakot' },
  { name: 'Umbrella Waterfall' },
  { name: 'Gilgit' },
  { name: 'Chilas' },
  { name: 'Babusar Top' },
  { name: 'Noori Waterfall' },
  { name: 'Lake View Park' },
  { name: 'Minar-E-Pakistan' },
  { name: 'Ayub National Park' },
  { name: 'Centaurs Mall' },
  { name: 'Markaz Islamabad' },
];
