import { Trip } from './entities/trip.entity';

export const trips: Trip[] = [
  {
    title: '',
    description: '',
    startDate: '',
    endDate: '',
    startDesitination: '',
    endDestination: '',
    totalDays: 0,
    totalSeats: 0,
    bookedSeats: 0,
    perPersonCharges: 0,
    coupleCharges: 0,
    familyCharges: 0,
    advancePayment: 0,
    roomSharing: 0,
    coverPhotoUrl: '',
    thumbnailUrl: '',
    placesIncluded: [''],
    servicesIncluded: [''],
    servicesExcluded: [''],
    isArchived: false,
    partnerId: '',
  },
  {
    title: '',
    description: '',
    startDate: '',
    endDate: '',
    startDesitination: '',
    endDestination: '',
    totalDays: 0,
    totalSeats: 0,
    bookedSeats: 0,
    perPersonCharges: 0,
    coupleCharges: 0,
    familyCharges: 0,
    advancePayment: 0,
    roomSharing: 0,
    coverPhotoUrl: '',
    thumbnailUrl: '',
    placesIncluded: [''],
    servicesIncluded: [''],
    servicesExcluded: [''],
    isArchived: false,
    partnerId: '',
  },
  {
    title: '',
    description: '',
    startDate: '',
    endDate: '',
    startDesitination: '',
    endDestination: '',
    totalDays: 0,
    totalSeats: 0,
    bookedSeats: 0,
    perPersonCharges: 0,
    coupleCharges: 0,
    familyCharges: 0,
    advancePayment: 0,
    roomSharing: 0,
    coverPhotoUrl: '',
    thumbnailUrl: '',
    placesIncluded: [''],
    servicesIncluded: [''],
    servicesExcluded: [''],
    isArchived: false,
    partnerId: '',
  },
  {
    title: '',
    description: '',
    startDate: '',
    endDate: '',
    startDesitination: '',
    endDestination: '',
    totalDays: 0,
    totalSeats: 0,
    bookedSeats: 0,
    perPersonCharges: 0,
    coupleCharges: 0,
    familyCharges: 0,
    advancePayment: 0,
    roomSharing: 0,
    coverPhotoUrl: '',
    thumbnailUrl: '',
    placesIncluded: [''],
    servicesIncluded: [''],
    servicesExcluded: [''],
    isArchived: false,
    partnerId: '',
  },
  {
    title: '',
    description: '',
    startDate: '',
    endDate: '',
    startDesitination: '',
    endDestination: '',
    totalDays: 0,
    totalSeats: 0,
    bookedSeats: 0,
    perPersonCharges: 0,
    coupleCharges: 0,
    familyCharges: 0,
    advancePayment: 0,
    roomSharing: 0,
    coverPhotoUrl: '',
    thumbnailUrl: '',
    placesIncluded: [''],
    servicesIncluded: [''],
    servicesExcluded: [''],
    isArchived: false,
    partnerId: '',
  },
];
